[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "project-lend"
version = "0.1.0"
description = "Autonomous food bank system with robotic sorting"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["lend*"]
